version: '3'

services: 
  mongo-express:
    restart: always
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: contadigital
      ME_CONFIG_BASICAUTH_PASSWORD: ContaDigital2020!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ContaDigital2020!
    links:
      - mongo
    networks:
      - mongo-network

  mongo:
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ContaDigital2020!
    ports:
      - "27017:27017"
    volumes:
      - ./volumes:/data/db
    networks:
      - mongo-network

networks: 
  mongo-network:
    driver: bridge